# Generated by Django 5.2.12 on 2026-03-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('total_score', models.IntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
                ('normalized_text', models.CharField(db_index=True, max_length=64)),
                ('language', models.CharField(choices=[('pl', 'Polski'), ('sk', 'Slovenský'), ('en', 'English')], max_length=2)),
                ('category', models.CharField(max_length=64)),
                ('hint', models.CharField(blank=True, max_length=128)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=64)),
                ('language', models.CharField(choices=[('pl', 'Polski'), ('sk', 'Slovenský'), ('en', 'English')], max_length=2)),
                ('guessed_letters', models.TextField(blank=True)),
                ('mistakes', models.PositiveSmallIntegerField(default=0)),
                ('max_mistakes', models.PositiveSmallIntegerField(default=11)),
                ('score_delta', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('won', 'Wygrana'), ('lost', 'Przegrana')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.player')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.word')),
            ],
        ),
    ]
