# Generated by Django 5.2.12 on 2026-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['language', 'category', 'text']},
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('language', 'text')},
        ),
    ]
