# Generated by Django 5.2.12 on 2026-03-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_room_mistake_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polski'), ('sk', 'Slovenčina'), ('cs', 'Čeština'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('nl', 'Nederlands'), ('pt', 'Português'), ('sv', 'Svenska')], max_length=2),
        ),
        migrations.AlterField(
            model_name='multiplayerparticipant',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polski'), ('sk', 'Slovenčina'), ('cs', 'Čeština'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('nl', 'Nederlands'), ('pt', 'Português'), ('sv', 'Svenska')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='multiplayerroom',
            name='current_word_language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polski'), ('sk', 'Slovenčina'), ('cs', 'Čeština'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('nl', 'Nederlands'), ('pt', 'Português'), ('sv', 'Svenska')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='multiplayerroom',
            name='host_language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polski'), ('sk', 'Slovenčina'), ('cs', 'Čeština'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('nl', 'Nederlands'), ('pt', 'Português'), ('sv', 'Svenska')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pl', 'Polski'), ('sk', 'Slovenčina'), ('cs', 'Čeština'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('nl', 'Nederlands'), ('pt', 'Português'), ('sv', 'Svenska')], max_length=2),
        ),
    ]
