# Generated by Django 5.2.12 on 2026-03-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gamesession_language_and_more'),
        ('game', '0007_room_coop_mode'),
    ]

    operations = [
    ]
